# Generated by Django 3.0.2 on 2020-01-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoturistico',
            options={'verbose_name': 'PontoTuristico'},
        ),
    ]
