# Generated by Django 3.0.2 on 2020-01-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atracao', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('horario_de_funcionamento', models.TextField()),
                ('idade_minima', models.IntegerField()),
                ('localizacao', models.TextField()),
            ],
            options={
                'verbose_name': 'Atracoe',
            },
        ),
    ]
