# Generated by Django 3.0.2 on 2020-01-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_auto_20200130_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracoes',
            options={'verbose_name': 'Atracoes'},
        ),
    ]
